---
title: "**Differential attrition in trials of novel antidiabetics:  A network meta-analysis
  of participant-level and aggregate-level data**"
subtitle: "**Statistical analysis plan**"
author: "Mr Ryan McChrystal MSc, Dr Peter Hanlon PhD, Professor David McAllister MD"
date: "2025-02-19"
output: html_document
bibliography: references.bib
csl: sage-vancouver.csl
---

---

### **1. Background and design**

#### **1.1 Background**
Novel antidiabetic drugs – dipeptidyl peptidase 4 inhibitors (DPP4i), glucagon-like peptide-1 receptor analogues (GLP1ra) and sodium glucose cotransport 2 inhibitors (SGLT2i) – have led recent advancements in the treatment of type 2 diabetes [@noauthor_overview_2022; @galindo_advances_2023; @schwartz_advances_2024]. This is supported by evidence from randomised controlled trials (hereafter termed trials) demonstrating improvements in glycaemia and reduced risk of cardiovascular events [@palmer_sodium-glucose_2021; @shi_benefits_2023; @hanlon_age_2025]. 

Attrition in trials of novel antidiabetics is generally low [@shaddinger_efficacy_2019; @ludvik_dulaglutide_2018; @hernandez_albiglutide_2018; @kaku_linagliptin_2019; @mullerwieland_efficacy_2018; @tinahones_linagliptin_2017; @ji_efficacy_2015; @white_randomized_2014; @matthaei_randomized_2015], but it is unclear whether it differs between treatment arms. Differences in attrition between treatment arms can threaten the internal validity of trials by biasing treatment effect estimates [@bell_differential_2013]. Therefore, as adoption of novel antidiabetics continues, it is important to understand whether differential attrition is occurring among these trials.

#### **1.2 Research hypothesis**
Trial attrition rates differ by treatment arm in trials of novel antidiabetics.

#### **1.3 Study aim**
Determine whether there are differences in attrition among participants receiving novel antidiabetics compared to those receiving a placebo or an active comparator in trials of novel antidiabetic.

#### **1.4 Study objectives**
i. Determine whether there are differences in attrition among participants who receive novel antidiabetics compared to participants who receive a placebo or active comparator in trials of DPP4i, SGLT2i, or GLP1ra.  
ii. Evaluate whether these differences differ by age or sex. 

### **2. Outcome**
The outcome will be attrition, defined as non-completion of a trial by a randomised participant for any reason up to the end of the protocol-defined follow-up.

### **3. Data sources**

#### **3.1 Trial identification**
Our research team conducted a systematic review and meta-analysis of novel antidiabetic drugs [@butterly_calibrating_2022; @hanlon_age_2025]. The inclusion criteria and identification process for these trials have previously been described. Briefly, eligible trials were phase III or IV trials of adults with type 2 diabetes comparing the efficacy of SGLT2i, GLP1ra or DDP4i in terms of assessing HbA1c, weight and/or major adverse cardiovascular events. After exclusions for reasons such as a lack of valid arm comparisons and/or disconnected treatments, 602 trials (103 for which we have access to IPD) were included in the published network meta-regression. 

From the set of 602 trials, trials where MACE is the primary outcome will be excluded as the end of follow-up in these trials is ambiguous (i.e. can occur at any time during follow-up). We will also exclude trials with fewer than 125 randomised participants.

#### **3.2 Data acquisition**
For IPD trials, we will calculate participation times between the dates of randomisation and dates of attrition (for non-completing participants) or completion (for completing participants). Participation times will be restricted to the protocol-defined duration of follow-up. We will index completion status as a binary event where 1 indicated attrition and 0 indicated trial completion. We will check the validity of our extractions by comparing obtained counts against participant flow statistics reported on clinicaltrials.gov or in clinical study reports. 

For aggregate-trials trials without IPD, we will extract arm-level data on attrition counts by treatment arm and follow-up duration via the aggregated analysis of ClinicalTrials.gov (AACT) database. Where attrition counts are not available via AACT, we will extract counts from published documents. One researcher will extract data in full, and a second researcher will perform an accuracy check in a random sample of 10%.

The extraction of age, sex and interventions has been described in previous work examining the heterogeneity of treatment effects on HbA1c by age and sex.  Briefly, drug names in IPD and aggregate-level data were extracted and categorised using the World Health Organisation Anatomical Therapeutic Chemical (WHO ATC) classification system (e.g. A10: Drugs used in diabetes; A10B: Blood glucose lowering drugs excl. insulins; A10BJ: Glucagon-like peptide-1 (GLP-1) analogues; A10BJ01: Exenatide). For objective 1, experimental and/or active comparator arms will be collapsed into their respective treatment class (i.e. insulins and analogues, biguanides, sulfonylureas, sulfonamides, alpha glucosidase inhibitors and thiazolidinediones). 

For both objectives, arm-level data will be processed as it was in the previous analysis (e.g. dropping combination arms).

### **4. Sample size calculations**

No sample size calculation will be performed because the study will use data from an existing available dataset.

### **5. Statistical analysis**
This analysis was specified after we identified that there were differences in attrition between participants receiving experimental treatments compared to those receiving placebo treatments in a subset of trials to be included in the current analysis (89 of the 103 IPD trials included in the published network meta-regression). This was initially done to inform the development of an attrition risk prediction model. However, the current analysis plan was specified before completing data extraction for a significant proportion of the trials for which we did not have access to IPD (49 of the 499 aggregate-level trials included in the published network meta-regression). 

All analyses will be conducted in R version 4.4 (R Foundation for Statistical Computing) using the *survival* [@therneau_survival_2001], *glm* [@R-base], and *multinma* [@phillippo_multinma_2020] packages. IPD summaries, aggregate-level data, summary statistics, model outputs and scripts written for preparation and analysis will be made available at the project GitHub repository.

For IPD trials, we previously fitted Cox proportional hazard and logistic regression models to compare the similarity of effect estimates. For treatment, age and age-treatment and sex-treatment interactions, we compared coefficients and standard errors for both the log-hazard and log-odds ratio. The outputs were similar, so we opted to use logistic regression models in the current analyses. We chose logistic regression over Cox models because it simplifies the analysis and limits data requirements to counts of participants and events by arm for each trial.

#### **Objective 1. Determine whether there are differences in attrition among participants who receive novel antidiabetics compared to participants who receive a placebo or active comparator in trials of DPP4i, SGLT2i and GLP1ra**
For objective 1, we will fit a one-stage multi-level network meta-analysis to the IPD and aggregate-level trial data. A one-stage approach will allow us to include trials with small numbers of events in each arm. Hierarchical Bayesian models will be fitted using a binomial likelihood with random effects for treatments. This will allow us to estimate odds ratios for the effect of each treatment class on attrition. Placebo will be used as the reference category in model fitting, but comparisons will be reported for all pairs of drug classes. Models will be estimated using Hamiltonian Markov Chain Monte Carlo sampling implemented in Stan. We will run four chains with 1000 iterations. Model convergence will be evaluated using the R-hat statistic and constructing trace plots. Posterior predictive checks will be performed by comparing summaries of observed data to predicted data. We will test for inconsistency in the network using node splitting [@dias_checking_2010]. Models will be summarised using the posterior mean and 95% credible intervals for treatment effect.

#### **Objective 2. Evaluate whether these differences differ by age or sex**
For objective 2, we will conduct a two-stage multi-level network meta-regression (ML-NMR) analysis. We are conducting a two-stage analysis because it is not possible to run the software required within the IPD safe haven, nor would it be possible to export IPD that would be required to fit a one-stage model. Although it is possible to include aggregate-level trials in estimating treatment-covariate interactions by integrating over the joint distributions of covariates [@phillippo_multilevel_2020], we will not do so for the current analysis because the models are more straightforward to fit. Additionally, many of the aggregate-level trials have comparatively few events. If resources allow, we will fit the more complex models (i.e. integrating over joint age-sex distribution for each arm) in additional analyses.

For the first step of the two-stage analysis, we will first fit logistic regression models of age, sex and interaction terms to each IPD trial. The model coefficients and variance-covariance matrices will then be exported from the Vivli environment. In the second step, we will fit Bayesian ML-NMR models using trial-level model coefficients and variance-covariance matrices. A multilevel normal likelihood will be specified and covariate-treatment interactions will be assumed to be common across treatment classes. The same convergence and posterior predictive checks will be performed for these models as done for the treatment effect NMA. To examine the effect of each main effect and interaction term separately, we will repeat this process with simpler trial-level models: i. Treatment alone, ii.) Treatment and age, iii.) Treatment and sex, iv.) Treatment, age and sex, v.) Treatment and age with interaction term, and vi.) Treatment and sex with interaction term.

### **6. References**
